server:
  port: 8082

spring:
  application:
    name: question-service

  datasource:
    url: jdbc:postgresql://localhost:5434/db_question
    username: postgres
    password: question_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect