server:
  port: 8083

spring:
  application:
    name: exam-service

  datasource:
    url: jdbc:postgresql://localhost:5435/db_exam
    username: postgres
    password: exam_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect